// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAym_KjR4Y48uKltd2INfNalJ3W6DjDlgk',
    appId: '1:357318229647:web:766991d477db411a64fafa',
    messagingSenderId: '357318229647',
    projectId: 'denun-pucminas',
    authDomain: 'denun-pucminas.firebaseapp.com',
    storageBucket: 'denun-pucminas.firebasestorage.app',
    measurementId: 'G-4RZJXKDBKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4YwKg2Q5MHPeT4W9YjOtbarNzLqpz66Q',
    appId: '1:357318229647:android:c4b6a4082854e15064fafa',
    messagingSenderId: '357318229647',
    projectId: 'denun-pucminas',
    storageBucket: 'denun-pucminas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxLaIbmYxG-vWg9JlAE46CMyTrWPE50Tw',
    appId: '1:357318229647:ios:5f87d8e7e5b2130364fafa',
    messagingSenderId: '357318229647',
    projectId: 'denun-pucminas',
    storageBucket: 'denun-pucminas.firebasestorage.app',
    iosBundleId: 'com.example.denun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxLaIbmYxG-vWg9JlAE46CMyTrWPE50Tw',
    appId: '1:357318229647:ios:5f87d8e7e5b2130364fafa',
    messagingSenderId: '357318229647',
    projectId: 'denun-pucminas',
    storageBucket: 'denun-pucminas.firebasestorage.app',
    iosBundleId: 'com.example.denun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAym_KjR4Y48uKltd2INfNalJ3W6DjDlgk',
    appId: '1:357318229647:web:66673b3dac87914c64fafa',
    messagingSenderId: '357318229647',
    projectId: 'denun-pucminas',
    authDomain: 'denun-pucminas.firebaseapp.com',
    storageBucket: 'denun-pucminas.firebasestorage.app',
    measurementId: 'G-TGSZQB0LLH',
  );

}